DROP TABLE IF EXISTS meals CASCADE;

CREATE TABLE meals (
  id SERIAL PRIMARY KEY NOT NULL,
  menu_id INTEGER NOT NULL,
  spoonacular_id INTEGER NOT NULL,
  title VARCHAR(255) NOT NULL,
  day VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  order_by INTEGER
);